//------------------------------------------------------------------------------
// <auto-generated>
//     Koden er generert av et verktøy.
//     Kjøretidsversjon:4.0.30319.42000
//
//     Endringer i denne filen kan føre til feil virkemåte, og vil gå tapt hvis
//     koden genereres på nytt.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 
namespace no.ks.fiks.io.arkivmelding.sok {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/sok")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/sok", IsNullable=false)]
    public partial class sok {
        
        private string systemField;
        
        private string meldingIdField;
        
        private System.DateTime tidspunktField;
        
        private int takeField;
        
        private int skipField;
        
        private respons_type responsField;
        
        private parameter[] parameterField;
        
        /// <remarks/>
        public string system {
            get {
                return this.systemField;
            }
            set {
                this.systemField = value;
            }
        }
        
        /// <remarks/>
        public string meldingId {
            get {
                return this.meldingIdField;
            }
            set {
                this.meldingIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime tidspunkt {
            get {
                return this.tidspunktField;
            }
            set {
                this.tidspunktField = value;
            }
        }
        
        /// <remarks/>
        public int take {
            get {
                return this.takeField;
            }
            set {
                this.takeField = value;
            }
        }
        
        /// <remarks/>
        public int skip {
            get {
                return this.skipField;
            }
            set {
                this.skipField = value;
            }
        }
        
        /// <remarks/>
        public respons_type respons {
            get {
                return this.responsField;
            }
            set {
                this.responsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("parameter")]
        public parameter[] parameter {
            get {
                return this.parameterField;
            }
            set {
                this.parameterField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/sok")]
    public enum respons_type {
        
        /// <remarks/>
        mappe,
        
        /// <remarks/>
        registrering,
        
        /// <remarks/>
        dokument,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/sok")]
    public partial class parameter {
        
        private string feltField;
        
        private operator_type operatorField;
        
        private parameterverdier parameterverdierField;
        
        /// <remarks/>
        public string felt {
            get {
                return this.feltField;
            }
            set {
                this.feltField = value;
            }
        }
        
        /// <remarks/>
        public operator_type @operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
            }
        }
        
        /// <remarks/>
        public parameterverdier parameterverdier {
            get {
                return this.parameterverdierField;
            }
            set {
                this.parameterverdierField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/sok")]
    public enum operator_type {
        
        /// <remarks/>
        equal,
        
        /// <remarks/>
        between,
        
        /// <remarks/>
        lessthan,
        
        /// <remarks/>
        greaterthan,
        
        /// <remarks/>
        inlist,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/sok")]
    public partial class parameterverdier {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("datevalues", typeof(datevalues))]
        [System.Xml.Serialization.XmlElementAttribute("intvalues", typeof(intvalues))]
        [System.Xml.Serialization.XmlElementAttribute("klassifikasjonvalues", typeof(klassifikasjonvalues))]
        [System.Xml.Serialization.XmlElementAttribute("stringvalues", typeof(stringvalues))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/sok")]
    public partial class datevalues {
        
        private System.DateTime[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("value")]
        public System.DateTime[] value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/sok")]
    public partial class klassifikasjonvalues {
        
        private string[] klassifikasjonssystemField;
        
        private string[] klasseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("klassifikasjonssystem")]
        public string[] klassifikasjonssystem {
            get {
                return this.klassifikasjonssystemField;
            }
            set {
                this.klassifikasjonssystemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("klasse")]
        public string[] klasse {
            get {
                return this.klasseField;
            }
            set {
                this.klasseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/sok")]
    public partial class intvalues {
        
        private int[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("value")]
        public int[] value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/sok")]
    public partial class stringvalues {
        
        private string[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("value")]
        public string[] value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
}
