//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 
namespace no.ks.fiks.io.arkivmelding.sok {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/sok")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/sok", IsNullable=false)]
    public partial class sok {
        
        private string systemField;
        
        private string meldingIdField;
        
        private System.DateTime tidspunktField;
        
        private int takeField;
        
        private int skipField;
        
        private respons_type responsField;
        
        private parameter[] parameterField;
        
        /// <remarks/>
        public string system {
            get {
                return this.systemField;
            }
            set {
                this.systemField = value;
            }
        }
        
        /// <remarks/>
        public string meldingId {
            get {
                return this.meldingIdField;
            }
            set {
                this.meldingIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime tidspunkt {
            get {
                return this.tidspunktField;
            }
            set {
                this.tidspunktField = value;
            }
        }
        
        /// <remarks/>
        public int take {
            get {
                return this.takeField;
            }
            set {
                this.takeField = value;
            }
        }
        
        /// <remarks/>
        public int skip {
            get {
                return this.skipField;
            }
            set {
                this.skipField = value;
            }
        }
        
        /// <remarks/>
        public respons_type respons {
            get {
                return this.responsField;
            }
            set {
                this.responsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("parameter")]
        public parameter[] parameter {
            get {
                return this.parameterField;
            }
            set {
                this.parameterField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/sok")]
    public enum respons_type {
        
        /// <remarks/>
        mappe,
        
        /// <remarks/>
        saksmappe,
        
        /// <remarks/>
        registrering,
        
        /// <remarks/>
        journalpost,
        
        /// <remarks/>
        dokumentbeskrivelse,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/sok")]
    public partial class parameter {
        
        private field_type feltField;
        
        private operator_type operatorField;
        
        private parameterverdier parameterverdierField;
        
        /// <remarks/>
        public field_type felt {
            get {
                return this.feltField;
            }
            set {
                this.feltField = value;
            }
        }
        
        /// <remarks/>
        public operator_type @operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
            }
        }
        
        /// <remarks/>
        public parameterverdier parameterverdier {
            get {
                return this.parameterverdierField;
            }
            set {
                this.parameterverdierField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/sok")]
    public enum field_type {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("mappe.eksternId")]
        mappeeksternId,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("mappe.tittel")]
        mappetittel,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("mappe.skjerming")]
        mappeskjerming,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("mappe.OpprettetDato")]
        mappeOpprettetDato,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("mappe.beskrivelse")]
        mappebeskrivelse,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("mappe.noekkelord")]
        mappenoekkelord,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("mappe.AvsluttetDato")]
        mappeAvsluttetDato,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("mappe.virksomhetsspesifikkeMetadata")]
        mappevirksomhetsspesifikkeMetadata,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("sak.saksdato")]
        saksaksdato,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("sak.saksaar")]
        saksaksaar,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("sak.saksekvensnummer")]
        saksaksekvensnummer,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("sak.saksstatus")]
        saksaksstatus,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("mappe.part.partNavn")]
        mappepartpartNavn,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("mappe.part.partRolle")]
        mappepartpartRolle,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("mappe.part.postadresse")]
        mappepartpostadresse,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("mappe.part.postnummer")]
        mappepartpostnummer,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("mappe.part.poststed")]
        mappepartpoststed,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("mappe.part.epostadresse")]
        mappepartepostadresse,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("mappe.part.virksomhetsspesifikkeMetadata")]
        mappepartvirksomhetsspesifikkeMetadata,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("registrering.eksternId")]
        registreringeksternId,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("registrering.tittel")]
        registreringtittel,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("registrering.skjerming")]
        registreringskjerming,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("registrering.part.partNavn")]
        registreringpartpartNavn,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("registrering.part.partRolle")]
        registreringpartpartRolle,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("registrering.part.postadresse")]
        registreringpartpostadresse,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("registrering.part.postnummer")]
        registreringpartpostnummer,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("registrering.part.poststed")]
        registreringpartpoststed,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("registrering.part.epostadresse")]
        registreringpartepostadresse,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("registrering.part.virksomhetsspesifikkeMetadata")]
        registreringpartvirksomhetsspesifikkeMetadata,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("journalpost.journalaar")]
        journalpostjournalaar,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("journalpost.journalsekvensnummer")]
        journalpostjournalsekvensnummer,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("journalpost.journalpostnummer")]
        journalpostjournalpostnummer,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("journalpost.journalposttype")]
        journalpostjournalposttype,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("journalpost.journalstatus")]
        journalpostjournalstatus,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("journalpost.journaldato")]
        journalpostjournaldato,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/sok")]
    public enum operator_type {
        
        /// <remarks/>
        equal,
        
        /// <remarks/>
        between,
        
        /// <remarks/>
        lessthan,
        
        /// <remarks/>
        lessequal,
        
        /// <remarks/>
        greaterthan,
        
        /// <remarks/>
        greaterequal,
        
        /// <remarks/>
        inlist,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/sok")]
    public partial class parameterverdier {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("datevalues", typeof(datevalues))]
        [System.Xml.Serialization.XmlElementAttribute("intvalues", typeof(intvalues))]
        [System.Xml.Serialization.XmlElementAttribute("klassifikasjonvalues", typeof(klassifikasjonvalues))]
        [System.Xml.Serialization.XmlElementAttribute("stringvalues", typeof(stringvalues))]
        [System.Xml.Serialization.XmlElementAttribute("virksomhetsspesifikkemetadata", typeof(vsmetadata))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/sok")]
    public partial class datevalues {
        
        private System.DateTime[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("value")]
        public System.DateTime[] value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/sok")]
    public partial class vsmetadata {
        
        private string[] keyField;
        
        private string[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("key")]
        public string[] key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("value")]
        public string[] value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/sok")]
    public partial class klassifikasjonvalues {
        
        private string[] klassifikasjonssystemField;
        
        private string[] klasseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("klassifikasjonssystem")]
        public string[] klassifikasjonssystem {
            get {
                return this.klassifikasjonssystemField;
            }
            set {
                this.klassifikasjonssystemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("klasse")]
        public string[] klasse {
            get {
                return this.klasseField;
            }
            set {
                this.klasseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/sok")]
    public partial class intvalues {
        
        private int[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("value")]
        public int[] value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/sok")]
    public partial class stringvalues {
        
        private string[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("value")]
        public string[] value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
}
