///////////////////////////////////////////////////////////
//  ArkivmeldingForenkletUtgaaende.cs
//  Implementation of the Class ArkivmeldingForenkletUtgaaende
//  Generated by Enterprise Architect
//  Created on:      27-mai-2020 09:33:14
//  Original author: TorKjetilNilsen
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FIKS.eMeldingArkiv.eMeldingForenkletArkiv;
namespace FIKS.eMeldingArkiv.eMeldingForenkletArkiv {
	public class ArkivmeldingForenkletUtgaaende {

		public Saksmappe referanseSaksmappe;
		public UtgaaendeJournalpost nyUtgaaendeJournalpost;
		public string sluttbrukerIdentifikator;

		public ArkivmeldingForenkletUtgaaende(){

		}

		~ArkivmeldingForenkletUtgaaende(){

		}

	}//end ArkivmeldingForenkletUtgaaende

}//end namespace eMeldingForenkletArkiv