///////////////////////////////////////////////////////////
//  ArkivmeldingForenkletInnkommende.cs
//  Implementation of the Class ArkivmeldingForenkletInnkommende
//  Generated by Enterprise Architect
//  Created on:      28-mai-2020 12:39:46
//  Original author: TorKjetilNilsen
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FIKS.eMeldingArkiv.eMeldingForenkletArkiv;
namespace FIKS.eMeldingArkiv.eMeldingForenkletArkiv {
	public class ArkivmeldingForenkletInnkommende {

		public Saksmappe referanseSaksmappe;
		public InnkommendeJournalpost nyInnkommendeJournalpost;
		public string sluttbrukerIdentifikator;

		public ArkivmeldingForenkletInnkommende(){

		}

		~ArkivmeldingForenkletInnkommende(){

		}

	}//end ArkivmeldingForenkletInnkommende

}//end namespace eMeldingForenkletArkiv