///////////////////////////////////////////////////////////
//  ArkivmeldingForenkletNotat.cs
//  Implementation of the Class ArkivmeldingForenkletNotat
//  Generated by Enterprise Architect
//  Created on:      18-aug-2020 10:59:12
//  Original author: TorKjetilNilsen
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FIKS.eMeldingArkiv.eMeldingForenkletArkiv;
namespace FIKS.eMeldingArkiv.eMeldingForenkletArkiv {
	public class ArkivmeldingForenkletNotat {

		public Saksmappe referanseSaksmappe;
		public OrganinterntNotat nyttNotat;
		public string sluttbrukerIdentifikator;

		public ArkivmeldingForenkletNotat(){

		}

		~ArkivmeldingForenkletNotat(){

		}

	}//end ArkivmeldingForenkletNotat

}//end namespace eMeldingForenkletArkiv