///////////////////////////////////////////////////////////
//  Enhetsidentifikator.cs
//  Implementation of the Class Enhetsidentifikator
//  Generated by Enterprise Architect
//  Created on:      02-jun-2020 09:21:39
//  Original author: Tor Kjetil
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace FIKS.eMeldingArkiv.eMeldingForenkletArkiv {
	public class Enhetsidentifikator {

		public string organisasjonsnummer;

		public Enhetsidentifikator(){

		}

		~Enhetsidentifikator(){

		}

	}//end Enhetsidentifikator

}//end namespace eMeldingForenkletArkiv