///////////////////////////////////////////////////////////
//  EnkelAdresse.cs
//  Implementation of the Class EnkelAdresse
//  Generated by Enterprise Architect
//  Created on:      02-jun-2020 09:21:24
//  Original author: Tor Kjetil
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;




namespace FIKS.eMeldingArkiv.eMeldingForenkletArkiv {
	public class EnkelAdresse {

		public string adresselinje1;
		public string adresselinje2;
		public string adresselinje3;
		public string postnr;
		public string poststed;
		public string landkode;

		public EnkelAdresse(){

		}

		~EnkelAdresse(){

		}

	}//end EnkelAdresse

}//end namespace eMeldingForenkletArkiv