///////////////////////////////////////////////////////////
//  ForenkletDokument.cs
//  Implementation of the Class ForenkletDokument
//  Generated by Enterprise Architect
//  Created on:      27-mai-2020 09:52:44
//  Original author: TorKjetilNilsen
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;




namespace FIKS.eMeldingArkiv.eMeldingForenkletArkiv {
	public class ForenkletDokument {

		/// <summary>
		/// Definisjon: Navn på type dokument
		/// 
		/// Kilde: Registreres automatisk av systemet eller manuelt
		/// 
		/// Kommentarer: (ingen)
		/// 
		/// M083
		/// </summary>
		//public Kodelister.Dokumenttype dokumenttype;
		/// <summary>
		/// veFilnavn i n4
		/// </summary>
		public string filnavn;
		/// <summary>
		/// Definisjon: Tittel eller navn på arkivenheten
		/// 
		/// Kilde: Registreres manuelt eller hentes automatisk fra innholdet i
		/// arkivdokumentet. Ja fra klassetittel dersom alle mapper skal ha samme tittel
		/// som klassen. Kan også hentes automatisk fra et fagsystem.
		/// 
		/// Kommentarer: For saksmappe og journalpost vil dette tilsvare "Sakstittel" og
		/// "Dokumentbeskrivelse". Disse navnene kan beholdes i grensesnittet.
		/// 
		/// M020
		/// </summary>
		public string tittel;
		public Boolean skjermetDokument;

		public ForenkletDokument(){

		}

		~ForenkletDokument(){

		}

	}//end ForenkletDokument

}//end namespace eMeldingForenkletArkiv