///////////////////////////////////////////////////////////
//  Kontaktinformasjon.cs
//  Implementation of the Class Kontaktinformasjon
//  Generated by Enterprise Architect
//  Created on:      02-jun-2020 09:21:36
//  Original author: Tor Kjetil
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace FIKS.eMeldingArkiv.eMeldingForenkletArkiv {
	public class Kontaktinformasjon {

		public string epostadresse;
		public string mobiltelefon;
		public string telefon;

		public Kontaktinformasjon(){

		}

		~Kontaktinformasjon(){

		}

	}//end Kontaktinformasjon

}//end namespace eMeldingForenkletArkiv