///////////////////////////////////////////////////////////
//  OppdaterSaksmappe.cs
//  Implementation of the Class OppdaterSaksmappe
//  Generated by Enterprise Architect
//  Created on:      24-aug-2020 14:10:05
//  Original author: TorKjetilNilsen
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FIKS.eMeldingArkiv.eMeldingForenkletArkiv;
namespace FIKS.eMeldingArkiv.eMeldingForenkletArkiv {
	public class OppdaterSaksmappe {

		public Saksmappe oppdaterSaksmappe;
		public string sluttbrukerIdentifikator;

		public OppdaterSaksmappe(){

		}

		~OppdaterSaksmappe(){

		}

	}//end OppdaterSaksmappe

}//end namespace eMeldingForenkletArkiv