///////////////////////////////////////////////////////////
//  OrganinterntNotat.cs
//  Implementation of the Class OrganinterntNotat
//  Generated by Enterprise Architect
//  Created on:      18-aug-2020 10:59:28
//  Original author: TorKjetilNilsen
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FIKS.eMeldingArkiv.eMeldingForenkletArkiv;
namespace FIKS.eMeldingArkiv.eMeldingForenkletArkiv {
	public class OrganinterntNotat {

		public ForenkletDokument hoveddokument;
		public EksternNøkkel referanseEksternNøkkel;
		public string tittel;
		public DateTime? dokumentetsDato;
		public List<KorrespondansepartIntern> internMottaker;
		public List<KorrespondansepartIntern> internAvsender;
		
		public List<ForenkletDokument> vedlegg;

		public OrganinterntNotat(){
			vedlegg = new List<ForenkletDokument>();
			
			internAvsender = new List<KorrespondansepartIntern>();
			internMottaker = new List<KorrespondansepartIntern>();
		}

		~OrganinterntNotat(){

		}

	}//end OrganinterntNotat

}//end namespace eMeldingForenkletArkiv