///////////////////////////////////////////////////////////
//  Personidentifikator.cs
//  Implementation of the Class Personidentifikator
//  Generated by Enterprise Architect
//  Created on:      02-jun-2020 09:21:42
//  Original author: tornil
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace FIKS.eMeldingArkiv.eMeldingForenkletArkiv {
	public class Personidentifikator {

		public string personidentifikatorNr;
		public string personidentifikatorType;

		public Personidentifikator(){

		}

		~Personidentifikator(){

		}

	}//end Personidentifikator

}//end namespace eMeldingForenkletArkiv