apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiks-arkiv-simulator-arkivsystem
  annotations:
    description: "Simulator for arkivsystem som kjorer som en console app"
    externalServices: "Fiks-io, maskinporten"
  labels:
    app: fiks-arkiv-simulator-arkivsystem
    component: fiks-arkiv-simulator-arkivsystem
    criticality: "NORMAL"
spec:
  replicas: 1
  minReadySeconds: 10
  revisionHistoryLimit: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      component: fiks-arkiv-simulator-arkivsystem
  template:
    metadata:
      labels:
        component: fiks-arkiv-simulator-arkivsystem
    spec:
      containers:
        - name: fiks-arkiv-simulator-arkivsystem
          image: "{{ .Values.image.repository }}fiks-arkiv-simulator-arkivsystem:{{ .Values.image.tag }}"
          env:
            - name: KUBERNETES_NODE
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName